@startuml  


title Components - Component Diagram

 node "web browser" {
  [Client]
  }
  

  
  node "web server" {
  [OpenServer]
  [CMS system]
  [PostgresSQL]
  }
  
  [Client] --> [OpenServer]: request
  [OpenServer] --> [PostgresSQL]: request
  [OpenServer] --> [CMS system]: request

@enduml
